version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: /run/secrets/postgres_user
      POSTGRES_PASSWORD: /run/secrets/postgres_password
      POSTGRES_NON_ROOT_USER: /run/secrets/postgres_non_root_user
      POSTGRES_NON_ROOT_PASSWORD: /run/secrets/postgres_non_root_password
      POSTGRES_DB: n8n
    secrets:
      - postgres_user
      - postgres_password
      - postgres_non_root_user
      - postgres_non_root_password
    volumes:
      - db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      GENERIC_TIMEZONE: Asia/Tokyo
      TZ: Asia/Tokyo
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: true
      DB_TYPE: n8n
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n
      DB_POSTGRESDB_USER: /run/secrets/postgres_non_root_user
      DB_POSTGRESDB_PASSWORD: /run/secrets/postgres_non_root_password
    secrets:
      - postgres_non_root_user
      - postgres_non_root_password
    ports:
      - 5678:5678
    links:
      - postgres
    volumes:
      - n8n_storage:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    

secrets:
  postgres_user:
    file: ./secrets/postgres_user.txt
  postgres_password:
    file: ./secrets/postgres_password.txt
  postgres_non_root_user:
    file: ./secrets/postgres_non_root_user.txt
  postgres_non_root_password:
    file: ./secrets/postgres_non_root_password.txt

volumes:
  db_storage:
  n8n_storage: